import Document, { Html, Head, Main, NextScript } from 'next/document'

export default class _document extends Document {

  render() {
    return (
      <Html>
        <Head>
          <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css"
          />
          <link rel="icon" href="/favicon.svg" />
          <meta name="description" content="Generated by create next app" />
          <meta charSet="UTF-8" />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta property="og:title" content="forthefuture" />
          <meta property="og:description" content="Cryptocurrency professionals, including traders, developers, and investors, value expertise and ethical adherence. Upholding responsibilities to the community, clients, and peers is paramount." />
          <meta property="og:url" content="https://www.f0rthefuture.com/" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
