import Document, { Html, Head, Main, NextScript } from 'next/document'

export default class _document extends Document {

  render() {
    return (
      <Html>
        <Head>
          <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css"
          />
          <link rel="icon" href="/favicon.svg" />
          <meta name="description" content="Generated by create next app" />
          <meta charSet="UTF-8" />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta property="og:title" content="#forthefuture" />
          <meta property="og:description" content="forthefuture is a member of the National Association of REALTORS® (NAR). REALTORS include agents who work as residential and commercial real estate brokers, salespeople, property managers, appraisers, counselors, and other real estate professionals. More than 1 million real estate agents are REALTORS. REALTORS are expected to be experts in their field and must follow NAR’s code of ethics, which requires agents to uphold specific duties to clients and customers, to the public, and to other REALTORS." />
          <meta property="og:url" content="https://www.f0rthefuture.com/" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
